#!/bin/bash
#set -x

WARN_ON_FAILURE=0
if [ "$1" = "--warn-on-failure" ]; then
    WARN_ON_FAILURE=1
    shift
fi

LANGUAGE="$1"
shift

FILES="$@"

if [ -z $(which linuxcnc-checklink) ]; then
    echo "ERROR: checklink no encontrado, instalar w3c-linkchecker para validacion de links HTML" 1>&2
    exit 1
fi


BAD_LINKS=0
for F in $FILES; do
    OUT=.checklink.$LANGUAGE.$(basename $F).tmp
    rm -f $OUT
    linuxcnc-checklink --quiet --exclude "http(s?)://" $F | tee $OUT 2>&1
    egrep -q 'Lista de (links rotos y otros asuntos|anclajes duplicados y vacios)' $OUT
    if [ $? -ne 1 ]; then
        BAD_LINKS=1
    fi
    rm -f $OUT
done

if [ $BAD_LINKS -eq 1 ]; then
    RET_VAL=1
    echo "***" 1>&2
    echo "*** Atencion: links incorrectos en documentos $LANGUAGE !" 1>&2
    if [ $WARN_ON_FAILURE -eq 1 ]; then
        echo "*** de acuerdo, continuo de todas formas" 1>&2
        RET_VAL=0
    fi
    echo "***" 1>&2
    exit $RET_VAL
else
    echo "###"
    echo "### lenguaje: $LANGUAGE"
    echo "### todos los links son correctos!"
    echo "###"
fi

fi

