#!/bin/bash

if [ ! -d debian -o ! -d src ]; then
    echo "este script debe ejecutarse desde la raíz del árbol fuente (el directorio con debian y src)"
    exit 1
fi


source scripts/githelper.sh
githelper $1

GIT_VERSION=$(scripts/get-version-from-git $GIT_BRANCH)
if [ $? -ne 0 ]; then
    echo "error al determinar version!"
    exit 1
fi

DEB_VERSION=`git show HEAD:debian/changelog | head -1 | sed 's/.*(\(.*\)).*/\1/'`

NEW_DEB_VERSION=$(echo $GIT_VERSION | sed -r 's/-pre/~pre/; s/-/./g')
NEW_DEB_VERSION="1:${NEW_DEB_VERSION/v/}"

if [ "$NEW_DEB_VERSION" = "$DEB_VERSION" ]; then
    echo "sin cambios desde la versión en la parte superior del archivo debian/changelog"
    echo "no se modifica debian/changelog"
    exit 0
fi

set -e
(
echo "linuxcnc ($NEW_DEB_VERSION) $(lsb_release -cs); urgency=low"
echo
git log --pretty=format:"  * %w(72,0,6)%s" $GIT_TAG..
echo
echo
echo " -- buildbot <buildbot@example.com>  $(date -R)"
echo
git show HEAD:debian/changelog
) > debian/changelog

dch -r --nomultimaint ""
