.\" Copyright (c) 2007 Alex Joni
.\"                (alex_joni AT users DOT sourceforge DOT net)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
.\" USA.
.\"
.\"
.\"
.TH AXIS "1"  "2007-04-01" "Documentación de LinuxCNC" "Controlador de máquina mejorado"
.SH NOMBRE
axis \- AXIS Interfaz gráfica de usuario de LinuxCNC
.SH SINOPSIS
.B axis
\fI\-ini\fR \fIINIFILE\fR
.SH DESCRIPCION
\fBaxis\fR es una de las interfaces gráficas de usuario (GUI) para LinuxCNC
Lo ejecuta runscript por lo general.
.SH OPCIONES
.TP
\fBINIFILE\fR
El archivo ini es la pieza principal de una configuración de LinuxCNC. No es la
configuración completa; hay muchos otros archivos que van con el
(archivos NML, archivos HAL, archivos TBL, archivos VAR). Sin embargo, es el más
importante, porque es el archivo que mantiene la configuración
junta. Puede ajustar muchos parámetros en sí mismo, pero también le dice a
\fBLinuxCNC\fR qué otros archivos cargar y usar.

.SH "VER TAMBIEN"
\fBLinuxCNC(1)\fR

Mucha más información sobre LinuxCNC y HAL está disponible en los manuales
de usuario de LinuxCNC y HAL, que se encuentran en /usr/share/doc/LinuxCNC/.

.SH HISTORIA

.SH BUGS
Ninguno conocido en este momento. 
.PP
.SH AUTOR
Esta página de manual escrita por Alex Joni, como parte del proyecto LinuxCNC.
.SH REPORTE DE BUGS
Informar errores a alex_joni AT users DOT sourceforge DOT net
.SH COPYRIGHT
Copyright \(co 2007 Alex Joni.
.br
Este es un software libre; ver la fuente de las condiciones de copia. NO hay
garantía; ni siquiera para COMERCIABILIDAD o IDONEIDAD PARA UN PROPÓSITO PARTICULAR.