.\" Copyright (c) 2014 Dewey Garrett
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
.\" USA.
.\"
.\"
.\"
TH moveoff_gui "1" "18/12/2014" "Documentación LinuxCNC" "LinuxCNC"
.SH NOMBRE
moveoff_gui \: una interfaz gráfica de usuario para el componente moveoff

.SH SINOPSIS
.B moveoff_gui \fB[\-\-help | \-\- \-h | \-?]\fR

.PP
.B moveoff_gui [\fBoptions\fR]
.PP

.SH DESCRIPCIÓN
Moveoff_gui es una interfaz gráfica de usuario (GUI) de muestra para
controlar un componente Hal moveoff para implementar
offsets solo de Hal. Vea la página de manual (man moveoff) para \fBlimitaciones y advertencias IMPORTANTES\fR.

Las configuraciones admitidas deben usar un módulo cinemático conocido con
\fBKINEMATICS_TYPE = KINEMATICS_IDENTITY\fR. Los módulos actualmente compatibles son:
   \fBtrivkins\fR

.SH OPCIONES

.TP
\ fB \ - \ - ayuda | \ -? El | \ - \ - \ -h \ fR
Mostrar opciones y salir

.TP
\fB\-mode\fR \fBonpause\fR | always
.br
onpause: gui emergente para controlar los offsets cuando el programa está en pausa
.br
always: siempre muestra la interfaz gráfica de usuario para controlar offsets
.br
Predeterminado: \fBonpause\fR

.TP
\fB\-axes\fR nombres de eje
.br
Letras del conjunto {x y z a b c u v w}
.br
Ejemplos: \-axes x, \-axes xyz, \-axes xz (sin espacios)
.br
Predeterminado: \fBxyz\fR

.TP
\fB\-inc\fR incremento
.br
Especifica un valor de incremento por \-inc (hasta 4)
.br
Valores predeterminados: \fB 0.001 0.01 0.10 1.0\fR

.TP
\fB\-size\fR entero
.br
El tamaño general de la interfaz gráfica de usuario se basa en el tamaño de fuente, generalmente 8-20
.br
Predeterminado: \fB14\fR

.TP
\fB\-loc\fR center | +x+y
.br
Ubicación inicial en pantalla
.br
Ejemplos: \-loc center, \-loc +20+100
.br
Valor predeterminado: \fBcenter\fR

.TP
\fB\-autoresume\fR
.br
Reanudar el programa cuando move-enable desactivado
.br
Predeterminado: no utilizado

.TP
\fB\-delay\fR retraso en segundos
.br
Retraso para el autoresume (permite tiempo para restaurar la velocidad del husillo, etc.)
Predeterminado: \fB5\fR

.SH OTRAS OPCIONES
Estas opciones están disponibles para casos especiales:

.TP
\fB\-noentry\fR
.br
Deshabilita la creación de widgets de entrada
.br
Predeterminado: no utilizado

.TP
\fB\-no_resume_inhibit\fR
.br
Desactiva el uso de resume\-inhibit para controlar la interfaz gráfica de usuario
.br
Predeterminado: no utilizado

.TP
\fB\-no_pause_requirement
.br
Desactivar la comprobación de halui.program.is\-paused
.br
Predeterminado: no utilizado

.TP
\fB\-no_cancel_autoresume
.br
Útil para retraer desplazamientos con controles externos simples
.br
Predeterminado: no utilizado

.TP
\fB\-no_display
.br
Úselo cuando los controles externos y las pantallas externas estén en uso
.br
Predeterminado: no utilizado

.SH NOTAS
LinuxCNC debe estar ejecutándose.
.P
Se debe cargar Halui, configuración típica del archivo ini:
    \fB[HAL]HALUI = halui\fR.
.PAGS
El componente moveoff debe cargarse con el nombre 'mv' como:
.br
    \fBloadrt moveoff names=mv personality=number_of_axes\fR
.P
Si el pin mv.motion\-enable \fBno\fR está conectado cuando moveoff_gui está
iniciada, se proporcionarán \fBcontroles\fR para habilitar los offsets y establecer
sus valores. Si el pin \fBesta\fR conectado, \fBsolo se muestra una pantalla\fR
de offsets y el control debe ser realizado por conexiones Hal \fBexternas\fR.
.P
Si un pin llamado *.resume\-inhibit existe y no está conectado, lo hará
establecerse mientras se aplican las compensaciones. Este pin puede ser proporcionado por el
controlando linuxcnc gui en uso. El uso del pin puede estar deshabilitado
con la opción \-no_resume_inhibit.
.P
La opción \-autoresume usa halui.program.resume para reanudar automáticamente
la ejecución del programa cuando el pin  move\-enable está desactivado
y se eliminan todos los offsets. El pin resume no está activado
hasta que transcurra un intervalo adicional (\-delay delay_secs). Este
intervalo de retraso puede ser útil para reiniciar el equipo relacionado
(un motor de husillo, por ejemplo). Mientras se cronometra el retraso, aparece una ventana emergente
que ofrece cancelar la reanudación automática del programa.

.SH USO
El archivo ini en el directorio de configuración debe proporcionar HALFILEs
para cargar el componente moveoff, conectar sus pines y agregar su
funciones de lectura y escritura en el orden correcto. Estos pasos pueden ser
hecho en tiempo de ejecución utilizando un archivo ini de configuración existente y
especificando una biblioteca del sistema HALFILE \fBhookup_moveoff.tcl\fR como se
ilustra a continuación:
.P
\fB[HAL]\fR
.br
HALUI = halui
.br
HALFILE = user_halfile_1
.br
etc ...
.br
HALFILE = user_halfile_n
.br
\fBHALFILE = LIB:hookup_moveoff.tcl\fR
.P
El halfile \fBhookup_moveoff.tcl\fR usará la configuración del archivo ini para
los pines de control del componente moveoff:
.P
\fB[OFFSET]\fR
.br
EPSILON =
.br
WAYPOINT_SAMPLE_SECS =
.br
WAYPOINT_THRESHOLD =
.br
BACKTRACK_ENABLE =
.P
\fBhookup_moveoff.tcl\fR usará la configuración del archivo ini para
los límites moveoff por eje:
.P
\fB[AXIS_m]\fR
.br
OFFSET_MAX_VELOCITY =
.br
OFFSET_MAX_ACCELERATION =
.br
OFFSET_MAX_LIMIT =
.br
OFFSET_MIN_LIMIT =
.PAGS
El programa moveoff_gui debe especificarse en APPLICATIONS
del archivo ini, por ejemplo:
.PAGS
\fB[APPLICATIONS]\fR
.br
DELAY = delay_in_secs_to_allow_hal_connections
.br
\fBAPP = moveoff_gui \-option1 \-option2 ...\fR
.P

.SH "VER TAMBIÉN"
Configuraciones de simulación que demuestran moveoff_gui y
moveoff se encuentra en:
.PAGS
   configs/sim/axis/moveoff (axis)
.br
   configs/sim/touchy/ngcgui (touchy)

página de manual para el componente: \fBmoveoff\fR(9)
